CREATE TABLE main
SELECT issue.DEFAULTED,issue.TENDER_EXCH_OFFER,issue.ANNOUNCED_CALL,issue.ACTIVE_ISSUE,issue.BOND_TYPE,issue.ISIN,issue.ACTION_TYPE,issue.EFFECTIVE_DATE,issue.CROSS_DEFAULT,issue.RATING_DECLINE_TRIGGER_PUT,issue.RATING_DECLINE_PROVISION,issue.FUNDED_DEBT_IS,issue.INDEBTEDNESS_IS,issue.FUNDED_DEBT_SUB,issue.INDEBTEDNESS_SUB,issue.CUSIP_NAME,issue.INDUSTRY_GROUP,issue.INDUSTRY_CODE,issue.ESOP,issue.IN_BANKRUPTCY,issue.PARENT_ID,issue.NAICS_CODE,issue.COUNTRY_DOMICILE,issue.SIC_CODE,ratings.*
FROM bond_credit.issue
INNER JOIN bond_credit.ratings USING (COMPLETE_CUSIP);